version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: standalone

  pipelineprobe:
    build: ../../
    volumes:
      - .:/app/quickstart
    environment:
      - PIPELINEPROBE_AIRFLOW_PASSWORD=admin
    depends_on:
      airflow:
        condition: service_started
    command: audit --config /app/quickstart/pipelineprobe.yml --format both
